backend:
  name: git-gateway
  branch: main
local_backend: true
publish_mode: editorial_workflow
media_folder: "public/images"
public_folder: "/images"
collections:
  - label: "Configuration"
    name: "configuration"
    files:
      - label: "Site Configuration"
        name: "site_configuration"
        delete: false
        create: true
        file: "_data/config.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
